version: "3.2"

services:
  dev:
    container_name: oak-testnet
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/oak-testnet
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/oak-testnet/.cargo
    volumes:
      - .:/var/www/oak-testnet
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/oak-testnet --dev --ws-external"
